// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {providers} from '../models';
import {terminal} from '../models';

export function CloseSession(arg1:string):Promise<void>;

export function ConnectProvider(arg1:string):Promise<void>;

export function GetProviders():Promise<Array<providers.Status>>;

export function ListSessions():Promise<Array<terminal.Info>>;

export function RefreshProviders():Promise<Array<providers.Status>>;

export function ResizeSession(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SelectFolder():Promise<string>;

export function StartSession(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number):Promise<terminal.Info>;

export function StopSession(arg1:string):Promise<void>;

export function WriteSession(arg1:string,arg2:string):Promise<void>;
