// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseSession(arg1) {
  return window['go']['main']['App']['CloseSession'](arg1);
}

export function ConnectProvider(arg1) {
  return window['go']['main']['App']['ConnectProvider'](arg1);
}

export function GetProviders() {
  return window['go']['main']['App']['GetProviders']();
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function RefreshProviders() {
  return window['go']['main']['App']['RefreshProviders']();
}

export function ResizeSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeSession'](arg1, arg2, arg3);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function StartSession(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['StartSession'](arg1, arg2, arg3, arg4, arg5);
}

export function StopSession(arg1) {
  return window['go']['main']['App']['StopSession'](arg1);
}

export function WriteSession(arg1, arg2) {
  return window['go']['main']['App']['WriteSession'](arg1, arg2);
}
